--------------------------------------------------------
--  Fichier créé - jeudi-février-19-2026   
--------------------------------------------------------
DROP TABLE "HICHEM"."PUBLICATIONS";
DROP TABLE "HICHEM"."FORMATIONS";
DROP TABLE "HICHEM"."LABS";
DROP TABLE "HICHEM"."CONGES";
DROP TABLE "HICHEM"."FINANCE";
DROP TABLE "HICHEM"."EMPLOYES";
DROP TABLE "HICHEM"."PRODUCT";
--------------------------------------------------------
--  DDL for Table PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PUBLICATIONS" 
   (	"ID_PUBLICATION" NUMBER, 
	"TITRE" VARCHAR2(500 BYTE), 
	"RESUME" VARCHAR2(2000 BYTE), 
	"INVENTEURS" VARCHAR2(500 BYTE), 
	"DOMAINE_FABRICATION" VARCHAR2(200 BYTE), 
	"TYPE_BREVET" VARCHAR2(100 BYTE), 
	"NUMERO_BREVET" NUMBER, 
	"DATE_DEPOT" DATE, 
	"STATUT_BREVET" VARCHAR2(50 BYTE) DEFAULT 'En cours', 
	"LIEN_DOCUMENT" VARCHAR2(30 BYTE), 
	"CINEMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATIONS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."FORMATIONS" 
   (	"ID_FORMATION" NUMBER, 
	"ID_EMPLOYE" NUMBER, 
	"THEME" VARCHAR2(200 BYTE), 
	"ORGANISME" VARCHAR2(150 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DUREE_JOURS" NUMBER GENERATED ALWAYS AS ("DATE_FIN"-"DATE_DEBUT"+1) VIRTUAL VISIBLE , 
	"COUT" NUMBER(12,2), 
	"STATUT" VARCHAR2(30 BYTE) DEFAULT 'Planifiï¿½e', 
	"VALORISATION" VARCHAR2(100 BYTE), 
	"DATE_INSCRIPTION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."LABS" 
   (	"IDLABO" NUMBER, 
	"RESPONSABLE" VARCHAR2(255 BYTE), 
	"LOCALISATION" VARCHAR2(10 BYTE), 
	"NUMERO" VARCHAR2(12 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"RESULTAT" VARCHAR2(255 BYTE), 
	"QRLABS" VARCHAR2(255 BYTE), 
	"NOMLABO" VARCHAR2(20 BYTE), 
	"CINEMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGES
--------------------------------------------------------

  CREATE TABLE "HICHEM"."CONGES" 
   (	"ID_CONGE" NUMBER, 
	"ID_EMPLOYE" NUMBER, 
	"TYPE_CONGE" VARCHAR2(50 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"JOURS" NUMBER GENERATED ALWAYS AS ("DATE_FIN"-"DATE_DEBUT"+1) VIRTUAL VISIBLE , 
	"STATUT" VARCHAR2(20 BYTE) DEFAULT 'En attente', 
	"DATE_DEMANDE" DATE DEFAULT SYSDATE, 
	"COMMENTAIRE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "HICHEM"."FINANCE" 
   (	"IDFINANCE" NUMBER, 
	"CODETRANSA" VARCHAR2(30 BYTE), 
	"TYPETRANSACTION" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER(10,2), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"DATETRANSACTION" DATE, 
	"MODEPAIEMENT" VARCHAR2(30 BYTE), 
	"DATECREATION" DATE, 
	"CINEMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "HICHEM"."EMPLOYES" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"POSTE" VARCHAR2(100 BYTE), 
	"DEPARTEMENT" VARCHAR2(100 BYTE), 
	"TYPE_CONTRAT" VARCHAR2(50 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"SALAIRE" NUMBER(10,2), 
	"DATE_POINTAGE" DATE, 
	"HEURES_TRAVAILLEES" NUMBER DEFAULT 0, 
	"HEURES_SUPPLEMENTAIRES" NUMBER DEFAULT 0, 
	"ABSENCE" CHAR(1 BYTE) DEFAULT 'N', 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'Employe'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PRODUCT" 
   (	"ID_PRODUCT" VARCHAR2(20 BYTE), 
	"SKU" VARCHAR2(20 BYTE), 
	"QT_AV" VARCHAR2(20 BYTE), 
	"QT_RS" VARCHAR2(20 BYTE), 
	"THRESHOLD" VARCHAR2(20 BYTE), 
	"SHELF" NUMBER, 
	"ZONE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"DESCR" VARCHAR2(50 BYTE), 
	"CINEMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HICHEM.PUBLICATIONS
SET DEFINE OFF;
REM INSERTING into HICHEM.FORMATIONS
SET DEFINE OFF;
REM INSERTING into HICHEM.LABS
SET DEFINE OFF;
REM INSERTING into HICHEM.CONGES
SET DEFINE OFF;
REM INSERTING into HICHEM.FINANCE
SET DEFINE OFF;
REM INSERTING into HICHEM.EMPLOYES
SET DEFINE OFF;
REM INSERTING into HICHEM.PRODUCT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_PUB_TITRE
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_PUB_TITRE" ON "HICHEM"."PUBLICATIONS" ("TITRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_PUB_DATE_DEPOT
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_PUB_DATE_DEPOT" ON "HICHEM"."PUBLICATIONS" ("DATE_DEPOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007029
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007029" ON "HICHEM"."PUBLICATIONS" ("ID_PUBLICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_FORM_EMP
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_FORM_EMP" ON "HICHEM"."FORMATIONS" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007032
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007032" ON "HICHEM"."FORMATIONS" ("ID_FORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_PK" ON "HICHEM"."LABS" ("IDLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_UK1" ON "HICHEM"."LABS" ("NOMLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_UK2" ON "HICHEM"."LABS" ("NOMLABO", "IDLABO", "QRLABS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_CONGE_EMP
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_CONGE_EMP" ON "HICHEM"."CONGES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007009
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007009" ON "HICHEM"."CONGES" ("ID_CONGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."FINANCE_PK" ON "HICHEM"."FINANCE" ("IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."UK" ON "HICHEM"."FINANCE" ("CODETRANSA", "IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007015" ON "HICHEM"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007016
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007016" ON "HICHEM"."EMPLOYES" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007017
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007017" ON "HICHEM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007018" ON "HICHEM"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007175
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007175" ON "HICHEM"."EMPLOYES" ("ID_EMPLOYE", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."PRODUCT_PK" ON "HICHEM"."PRODUCT" ("ID_PRODUCT", "SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("CINEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD PRIMARY KEY ("ID_PUBLICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CHECK (statut_brevet IN ('En cours','Dï¿½posï¿½','Acceptï¿½','Refusï¿½','Publiï¿½')) ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("TITRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FORMATIONS" ADD PRIMARY KEY ("ID_FORMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FORMATIONS" ADD CHECK (statut IN ('Planifiï¿½e','En cours','Terminï¿½e','Annulï¿½e')) ENABLE;
  ALTER TABLE "HICHEM"."FORMATIONS" MODIFY ("THEME" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FORMATIONS" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" MODIFY ("CINEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("IDLABO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("LOCALISATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESULTAT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("QRLABS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_PK" PRIMARY KEY ("IDLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_CHK1" CHECK (SPECIALITE IN ('interieur','exterieur')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_CHK2" CHECK (DISPONIBILITE IN ('Disponible','Occupe')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_UK1" UNIQUE ("NOMLABO", "IDLABO", "QRLABS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONGES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."CONGES" ADD PRIMARY KEY ("ID_CONGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."CONGES" ADD CHECK (statut IN ('En attente','Approuvï¿½','Refusï¿½','Annulï¿½')) ENABLE;
  ALTER TABLE "HICHEM"."CONGES" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."CONGES" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."CONGES" MODIFY ("TYPE_CONGE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."CONGES" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CINEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "UK" UNIQUE ("CODETRANSA", "IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_CHK1" CHECK (MODEPAIEMENT IN ('especes','cheque','virement','carte_bancaire','facture','remboursement')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MODEPAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_CHK_TYPETRANS" CHECK (typeTransaction IN ('Dépense','Revenu')
) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_PK" PRIMARY KEY ("IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("IDFINANCE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATECREATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("TYPETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CODETRANSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_UK1_ID" UNIQUE ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_UK_CIN" UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "SYS_C007175" PRIMARY KEY ("ID_EMPLOYE", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CHECK (role IN ('Admin', 'Chercheur', 'Technicien', 'Chef de projet', 'Employe')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CHECK (absence IN ('O','N')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("DATE_EMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("CINEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_CHK1" CHECK (status IN ('on hand','limited','stock out')) ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID_PRODUCT", "SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("QT_AV" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("SKU" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUBLICATIONS_FK1" FOREIGN KEY ("CINEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("CIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FORMATIONS" ADD CONSTRAINT "FORMATIONS_FK1" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_FK1" FOREIGN KEY ("CINEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("CIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."CONGES" ADD CONSTRAINT "CONGES_FK1" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_FK1" FOREIGN KEY ("CINEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("CIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_FK1" FOREIGN KEY ("CINEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("CIN") ON DELETE CASCADE ENABLE;
