--------------------------------------------------------
--  Fichier créé - mercredi-avril-01-2026   
--------------------------------------------------------
DROP TABLE "HICHEM"."LABS";
DROP TABLE "HICHEM"."EMPLOYES";
DROP TABLE "HICHEM"."FINANCE";
DROP TABLE "HICHEM"."PRODUCT";
DROP TABLE "HICHEM"."PROJETS";
DROP TABLE "HICHEM"."PUBLICATIONS";
--------------------------------------------------------
--  DDL for Table LABS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."LABS" 
   (	"IDLABO" NUMBER, 
	"RESPONSABLE" VARCHAR2(255 BYTE), 
	"LOCALISATION" VARCHAR2(50 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"RESULTAT" VARCHAR2(255 BYTE), 
	"NOMLABO" VARCHAR2(50 BYTE), 
	"IDEMP" NUMBER, 
	"PAIEMENT" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER(10,2) DEFAULT 0, 
	"MONTANT_PAYE" NUMBER(10,2) DEFAULT 0, 
	"RESTE" NUMBER(10,2) GENERATED ALWAYS AS ("MONTANT"-"MONTANT_PAYE") VIRTUAL VISIBLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "HICHEM"."EMPLOYES" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"POSTE" VARCHAR2(100 BYTE), 
	"DEPARTEMENT" VARCHAR2(100 BYTE), 
	"DATE_EMBAUCHE" DATE DEFAULT SYSDATE, 
	"SALAIRE" NUMBER(10,2), 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'Employe', 
	"TYPE_DEMANDE" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"DATE_DEMANDE" DATE, 
	"STATUT_DEMANDE" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_RH" VARCHAR2(255 BYTE) DEFAULT 'aucun', 
	"DATE_POINTAGE" DATE, 
	"HEURE_ARRIVEE" VARCHAR2(5 BYTE), 
	"HEURE_DEPART" VARCHAR2(5 BYTE), 
	"STATUT_JOURNALIER" VARCHAR2(20 BYTE), 
	"NB_ABSENCES" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "HICHEM"."FINANCE" 
   (	"IDFINANCE" NUMBER, 
	"CODETRANSA" VARCHAR2(30 BYTE), 
	"TYPETRANSACTION" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER(10,2), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"DATETRANSACTION" DATE, 
	"MODEPAIEMENT" VARCHAR2(30 BYTE), 
	"DATECREATION" DATE, 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PRODUCT" 
   (	"ID_PRODUCT" NUMBER, 
	"SKU" VARCHAR2(20 BYTE), 
	"QT_AV" NUMBER DEFAULT 0, 
	"QT_RS" NUMBER DEFAULT 0, 
	"THRESHOLD" NUMBER DEFAULT 0, 
	"SHELF" NUMBER, 
	"ZONE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"DESCR" VARCHAR2(50 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJETS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PROJETS" 
   (	"ID_PROJET" NUMBER, 
	"NOM_PROJET" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"OBJECTIFS" VARCHAR2(100 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN_PREVUE" DATE, 
	"DATE_FIN_REELLE" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"PRIORITE" VARCHAR2(20 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PUBLICATIONS" 
   (	"ID_PUBLICATION" NUMBER, 
	"TITRE" VARCHAR2(500 BYTE), 
	"RESUME" VARCHAR2(2000 BYTE), 
	"INVENTEURS" VARCHAR2(500 BYTE), 
	"DOMAINE_FABRICATION" VARCHAR2(200 BYTE), 
	"TYPE_BREVET" VARCHAR2(100 BYTE), 
	"NUMERO_BREVET" NUMBER, 
	"DATE_DEPOT" DATE, 
	"STATUT_BREVET" VARCHAR2(50 BYTE) DEFAULT 'En cours', 
	"LIEN_DOCUMENT" VARCHAR2(100 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HICHEM.LABS
SET DEFINE OFF;
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT,MONTANT,MONTANT_PAYE) values ('2','zak','morneg','92985300','exterieur','Occupe','En attente','vw','6','non payer','0','0');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT,MONTANT,MONTANT_PAYE) values ('3','zak','36°49''38.7"N 10°08''50.1"E','44845113','interieur','Occupe','En attente','mercedes','1','payer','0','0');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT,MONTANT,MONTANT_PAYE) values ('5','zza','36.82216689659118, 10.190769713391115','43','exterieur','Disponible','Prêt','aaa','1','non payer','0','0');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT,MONTANT,MONTANT_PAYE) values ('6','saaaaas','36.82216689659118, 10.190769713391115','creec','exterieur','Occupe','En attente','asazas','1','payer','0','0');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT,MONTANT,MONTANT_PAYE) values ('7','ayari','mourouj 4','92985230','interieur','Occupe','En attente','aynar','1','payer','0','0');
REM INSERTING into HICHEM.EMPLOYES
SET DEFINE OFF;
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('1','12345678','bo','Zak','ZAAK','5959bc63e1fbf0f1e5ff7d74884bf4b98310ec0f1fa9df459092e46e28bcb8fa','zak@gmail.com','RH','RH',to_date('25/03/26','DD/MM/RR'),'2300','RH',null,null,null,null,null,null,'aucun',null,null,null,'Absent','8');
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('5','12345269','BIB','IBI','BIBOU','hash','bibou@mail.com','Chercheur','Recherche',to_date('25/03/26','DD/MM/RR'),'2800','Chercheur',null,null,null,null,null,null,'aucun',null,null,null,'Absent','10');
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('6','12345633','toutou','toutou','tou','ea4ad5ed6b7b124a53aa2c22c35b9d67c20d2cc9e0ae03b971dac20cc4ef7871','TOUTOU@gmail.com','labs','labs',to_date('01/01/14','DD/MM/RR'),'2200','Admin',null,null,null,null,null,null,'aucun',null,null,null,null,'0');
REM INSERTING into HICHEM.FINANCE
SET DEFINE OFF;
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('1','trx','Revenu','405,19','lab',null,to_date('05/03/26','DD/MM/RR'),'facture',to_date('01/04/26','DD/MM/RR'),'6');
REM INSERTING into HICHEM.PRODUCT
SET DEFINE OFF;
Insert into HICHEM.PRODUCT (ID_PRODUCT,SKU,QT_AV,QT_RS,THRESHOLD,SHELF,ZONE,STATUS,TYPE,NAME,UNIT,PRICE,DESCR,IDEMP) values ('1','ZER-232','0','0','0','0','B','on hand','Outil','TEST','kg','4','EAZR','1');
REM INSERTING into HICHEM.PROJETS
SET DEFINE OFF;
REM INSERTING into HICHEM.PUBLICATIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007670
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007670" ON "HICHEM"."LABS" ("IDLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007671
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007671" ON "HICHEM"."LABS" ("NOMLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007644
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007644" ON "HICHEM"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007645
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007645" ON "HICHEM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007646
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007646" ON "HICHEM"."EMPLOYES" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007647
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007647" ON "HICHEM"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007658
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007658" ON "HICHEM"."FINANCE" ("IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007677
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007677" ON "HICHEM"."PRODUCT" ("ID_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007678
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007678" ON "HICHEM"."PRODUCT" ("SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007682
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007682" ON "HICHEM"."PROJETS" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007687
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007687" ON "HICHEM"."PUBLICATIONS" ("ID_PUBLICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" MODIFY ("NOMLABO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" ADD UNIQUE ("NOMLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD PRIMARY KEY ("IDLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_DISP_CHK" CHECK (DISPONIBILITE IN ('Disponible','Occupe')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_SPEC_CHK" CHECK (SPECIALITE IN ('interieur','exterieur')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("MONTANT_PAYE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("LOCALISATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_TYPE_CHK" CHECK (TYPE_DEMANDE IN ('CONGE','FORMATION')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_STATUT_CHK" CHECK (STATUT_DEMANDE IN ('EN_ATTENTE','ACCEPTE','REFUSE')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_DATE_CHK" CHECK (DATE_DEBUT IS NULL OR DATE_FIN IS NULL OR DATE_DEBUT <= DATE_FIN) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_ROLE_CHK" CHECK (ROLE IN 
    ('Admin','Employe','RH','Responsable_financier','Responsable_de_stock','Chercheur','Directeur_de_projet','Responsable_Labos')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("DATE_EMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD PRIMARY KEY ("IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_MODE_CHK" CHECK (MODEPAIEMENT IN 
        ('especes','cheque','virement','carte_bancaire','facture','remboursement')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_TYPE_CHK" CHECK (TYPETRANSACTION IN ('Depense','Revenu')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATECREATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MODEPAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("TYPETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CODETRANSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD UNIQUE ("SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_STATUS_CHK" CHECK (STATUS IN ('on hand','limited','stock out')) ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("SKU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_DATE_CHK" CHECK (
        DATE_FIN_REELLE IS NULL OR DATE_DEBUT < DATE_FIN_REELLE
    ) ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" MODIFY ("NOM_PROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD PRIMARY KEY ("ID_PUBLICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUB_STATUT_CHK" CHECK (STATUT_BREVET IN ('En cours','Depose','Accepte','Refuse','Publie')) ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("TITRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUB_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
