--------------------------------------------------------
--  File created - Thursday-February-26-2026   
--------------------------------------------------------
DROP TABLE "HICHEM"."PUBLICATIONS";
DROP TABLE "HICHEM"."PROJETS";
DROP TABLE "HICHEM"."PRODUCT";
DROP TABLE "HICHEM"."LABS";
DROP TABLE "HICHEM"."FINANCE";
DROP TABLE "HICHEM"."EMPLOYES";
--------------------------------------------------------
--  DDL for Table PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PUBLICATIONS" 
   (	"ID_PUBLICATION" NUMBER, 
	"TITRE" VARCHAR2(500 BYTE), 
	"RESUME" VARCHAR2(2000 BYTE), 
	"INVENTEURS" VARCHAR2(500 BYTE), 
	"DOMAINE_FABRICATION" VARCHAR2(200 BYTE), 
	"TYPE_BREVET" VARCHAR2(100 BYTE), 
	"NUMERO_BREVET" NUMBER, 
	"DATE_DEPOT" DATE, 
	"STATUT_BREVET" VARCHAR2(50 BYTE) DEFAULT 'En cours', 
	"LIEN_DOCUMENT" VARCHAR2(30 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJETS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PROJETS" 
   (	"ID_PROJET" NUMBER, 
	"NOM_PROJET" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"OBJECTIFS" VARCHAR2(100 BYTE), 
	"DATE_DÉBUT" DATE, 
	"DATE_FIN_PREVUE" DATE, 
	"DATE_FIN_REELLE" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"PRIORITE" VARCHAR2(20 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PRODUCT" 
   (	"ID_PRODUCT" VARCHAR2(20 BYTE), 
	"SKU" VARCHAR2(20 BYTE), 
	"QT_AV" VARCHAR2(20 BYTE), 
	"QT_RS" VARCHAR2(20 BYTE), 
	"THRESHOLD" VARCHAR2(20 BYTE), 
	"SHELF" NUMBER, 
	"ZONE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"DESCR" VARCHAR2(50 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."LABS" 
   (	"IDLABO" NUMBER, 
	"RESPONSABLE" VARCHAR2(255 BYTE), 
	"LOCALISATION" VARCHAR2(10 BYTE), 
	"NUMERO" VARCHAR2(12 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"RESULTAT" VARCHAR2(255 BYTE), 
	"QRLABS" VARCHAR2(255 BYTE), 
	"NOMLABO" VARCHAR2(20 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "HICHEM"."FINANCE" 
   (	"IDFINANCE" NUMBER, 
	"CODETRANSA" VARCHAR2(30 BYTE), 
	"TYPETRANSACTION" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER(10,2), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"DATETRANSACTION" DATE, 
	"MODEPAIEMENT" VARCHAR2(30 BYTE), 
	"DATECREATION" DATE, 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "HICHEM"."EMPLOYES" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"POSTE" VARCHAR2(100 BYTE), 
	"DEPARTEMENT" VARCHAR2(100 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"SALAIRE" NUMBER(10,2), 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'Employe', 
	"TYPE_DEMANDE" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"DATE_DEMANDE" DATE, 
	"STATUT_DEMANDE" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_RH" VARCHAR2(255 BYTE) DEFAULT 'aucun', 
	"DATE_POINTAGE" DATE, 
	"HEURE_ARRIVEE" VARCHAR2(5 BYTE), 
	"HEURE_DEPART" VARCHAR2(5 BYTE), 
	"STATUT_JOURNALIER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HICHEM.PUBLICATIONS
SET DEFINE OFF;
Insert into HICHEM.PUBLICATIONS (ID_PUBLICATION,TITRE,RESUME,INVENTEURS,DOMAINE_FABRICATION,TYPE_BREVET,NUMERO_BREVET,DATE_DEPOT,STATUT_BREVET,LIEN_DOCUMENT,IDEMP) values (2,'EEEEE','EEE','FSEF','ZEFZEF',null,2,to_date('01-JAN-00','DD-MON-RR'),'En cours',null,3);
Insert into HICHEM.PUBLICATIONS (ID_PUBLICATION,TITRE,RESUME,INVENTEURS,DOMAINE_FABRICATION,TYPE_BREVET,NUMERO_BREVET,DATE_DEPOT,STATUT_BREVET,LIEN_DOCUMENT,IDEMP) values (1,'test rayeeen','eee','eee','tunisieEEE',null,2,to_date('01-JAN-00','DD-MON-RR'),'En cours',null,3);
REM INSERTING into HICHEM.PROJETS
SET DEFINE OFF;
REM INSERTING into HICHEM.PRODUCT
SET DEFINE OFF;
Insert into HICHEM.PRODUCT (ID_PRODUCT,SKU,QT_AV,QT_RS,THRESHOLD,SHELF,ZONE,STATUS,TYPE,NAME,UNIT,PRICE,DESCR,IDEMP) values ('1','ABC-123','0','0','0',0,null,'limited',null,'EFEFUY6YI',null,0,null,1);
REM INSERTING into HICHEM.LABS
SET DEFINE OFF;
REM INSERTING into HICHEM.FINANCE
SET DEFINE OFF;
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values (3,'vezaeazer','D?pense',1212,'TEST','TEST',to_date('23-FEB-26','DD-MON-RR'),'facture',to_date('23-FEB-26','DD-MON-RR'),2);
REM INSERTING into HICHEM.EMPLOYES
SET DEFINE OFF;
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER) values (1,'12345678','bo','Zak','ZAAK','5959bc63e1fbf0f1e5ff7d74884bf4b98310ec0f1fa9df459092e46e28bcb8fa','ZAK@gmail.com','RH','RH',to_date('01-JAN-04','DD-MON-RR'),2300,'RH',null,null,null,null,null,null,'aucun',null,null,null,null);
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER) values (2,'14674451','toutou','toutou','TOUTOU','68930c70be0483afcc87e7fc8fd73097c62d1dba4cb0b2bdbe8c4b563036202f','TOUTOU@gmail.com','LABS','LABS',to_date('01-APR-00','DD-MON-RR'),1400,'Responsable_Labos',null,null,null,null,null,null,'aucun',null,null,null,null);
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER) values (3,'21723458','hagui','rayen','RAYY','8889c7344d03b4c0defee958dce0245f3b0cf684e7fb2d802b8f07a74118966b','rrayyyrrayyy@gmail.com','chercheur','chercheur',to_date('05-MAR-05','DD-MON-RR'),2000,'Chercheur',null,null,null,null,null,null,'aucun',null,null,null,null);
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER) values (4,'12348765','hich','chalakhi','hichem','2fdd4315931b1ecba55f46888b5ee8f8f44e50ec01ec9de9f025c60424be3af4','hichem@gmail.com','fin','fin',to_date('01-JAN-10','DD-MON-RR'),2010,'Responsable_financier',null,null,null,null,null,null,'aucun',null,null,null,null);
--------------------------------------------------------
--  DDL for Index IDX_PUB_TITRE
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_PUB_TITRE" ON "HICHEM"."PUBLICATIONS" ("TITRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_PUB_DATE_DEPOT
--------------------------------------------------------

  CREATE INDEX "HICHEM"."IDX_PUB_DATE_DEPOT" ON "HICHEM"."PUBLICATIONS" ("DATE_DEPOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007029
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007029" ON "HICHEM"."PUBLICATIONS" ("ID_PUBLICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROJETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."PROJETS_PK" ON "HICHEM"."PROJETS" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."PRODUCT_PK" ON "HICHEM"."PRODUCT" ("ID_PRODUCT", "SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_PK" ON "HICHEM"."LABS" ("IDLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_UK1" ON "HICHEM"."LABS" ("NOMLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LABS_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."LABS_UK2" ON "HICHEM"."LABS" ("NOMLABO", "IDLABO", "QRLABS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."FINANCE_PK" ON "HICHEM"."FINANCE" ("IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."UK" ON "HICHEM"."FINANCE" ("CODETRANSA", "IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007015" ON "HICHEM"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007016
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007016" ON "HICHEM"."EMPLOYES" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007017
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007017" ON "HICHEM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007018" ON "HICHEM"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HICHEM"."EMPLOYES_TRG1" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "HICHEM"."EMPLOYES_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HICHEM"."EMPLOYES_TRG2" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "HICHEM"."EMPLOYES_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG4
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HICHEM"."EMPLOYES_TRG4" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "HICHEM"."EMPLOYES_TRG4" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG3
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HICHEM"."EMPLOYES_TRG3" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "HICHEM"."EMPLOYES_TRG3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HICHEM"."EMPLOYES_TRG" 
BEFORE INSERT ON EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "HICHEM"."EMPLOYES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD PRIMARY KEY ("ID_PUBLICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CHECK (statut_brevet IN ('En cours','D?pos?','Accept?','Refus?','Publi?')) ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("TITRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_CHK2" CHECK ("DATE_FIN_REELLE" IS NULL OR "DATE_FIN_PREVUE" <= "DATE_FIN_REELLE") ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_CHK1" CHECK (DATE_FIN_REELLE IS NULL OR DATE_FIN_REELLE > DATE_DÉBUT) ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_PK" PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" MODIFY ("NOM_PROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_CHK1" CHECK (status IN ('on hand','limited','stock out')) ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID_PRODUCT", "SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("QT_AV" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("SKU" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("IDLABO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("LOCALISATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESULTAT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("QRLABS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_PK" PRIMARY KEY ("IDLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_CHK1" CHECK (SPECIALITE IN ('interieur','exterieur')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_CHK2" CHECK (DISPONIBILITE IN ('Disponible','Occupe')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_UK1" UNIQUE ("NOMLABO", "IDLABO", "QRLABS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "UK" UNIQUE ("CODETRANSA", "IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_CHK1" CHECK (MODEPAIEMENT IN ('especes','cheque','virement','carte_bancaire','facture','remboursement')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MODEPAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_CHK_TYPETRANS" CHECK (typeTransaction IN ('D?pense','Revenu')
) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_PK" PRIMARY KEY ("IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("IDFINANCE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATECREATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("TYPETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CODETRANSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_CHK1" CHECK (TYPE_DEMANDE IN ('CONGE,''FORMATION')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_CHK2" CHECK (statut_demande IN ('EN_ATTENTE ','ACCEPTE','REFUSE')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_CHK3" CHECK (date_debut IS NULL OR date_fin IS NULL OR date_debut <= date_fin
) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_CHK4" CHECK (heure_depart > heure_arrivee) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_UK1_ID" UNIQUE ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_UK_CIN" UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "SYS_C007108" CHECK (role IN ('Admin', 'Employe','RH','Responsable_financier','Responsable_de_stock','Chercheur','Directeur_de_projet','Responsable_Labos' )) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("DATE_EMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUBLICATIONS_FK1" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_FK1" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_FK1" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_FK1" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_FK1" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
