-- Fix missing columns causing ORA-00904 errors on CHEF login
ALTER TABLE EMPLOYES ADD FACE_ENCODING VARCHAR2(4000);
ALTER TABLE LABS ADD MONTANT NUMBER(10,2) DEFAULT 0;
ALTER TABLE LABS ADD MONTANT_PAYE NUMBER(10,2) DEFAULT 0;
