--------------------------------------------------------
--  Fichier créé - vendredi-mars-27-2026   
<<<<<<< HEAD
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYES_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."EMPLOYES_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYES_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."EMPLOYES_SEQ4"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONGE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."SEQ_CONGE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYE_ID
--------------------------------------------------------

=======

   CREATE SEQUENCE  "HICHEM"."CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYES_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."EMPLOYES_SEQ3"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYES_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."EMPLOYES_SEQ4"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONGE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."SEQ_CONGE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EMPLOYE_ID
--------------------------------------------------------

>>>>>>> 30b3d73efc0a4d3e01011549819f8cf3b40fa692
   CREATE SEQUENCE  "HICHEM"."SEQ_EMPLOYE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FORMATION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."SEQ_FORMATION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PUBLICATION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "HICHEM"."SEQ_PUBLICATION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "HICHEM"."EMPLOYES" 
   (	"ID_EMPLOYE" NUMBER, 
	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"POSTE" VARCHAR2(100 BYTE), 
	"DEPARTEMENT" VARCHAR2(100 BYTE), 
	"DATE_EMBAUCHE" DATE DEFAULT SYSDATE, 
	"SALAIRE" NUMBER(10,2), 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'Employe', 
	"TYPE_DEMANDE" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"DATE_DEMANDE" DATE, 
	"STATUT_DEMANDE" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_RH" VARCHAR2(255 BYTE) DEFAULT 'aucun', 
	"DATE_POINTAGE" DATE, 
	"HEURE_ARRIVEE" VARCHAR2(5 BYTE), 
	"HEURE_DEPART" VARCHAR2(5 BYTE), 
	"STATUT_JOURNALIER" VARCHAR2(20 BYTE), 
	"NB_ABSENCES" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "HICHEM"."FINANCE" 
   (	"IDFINANCE" NUMBER, 
	"CODETRANSA" VARCHAR2(30 BYTE), 
	"TYPETRANSACTION" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER(10,2), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"DATETRANSACTION" DATE, 
	"MODEPAIEMENT" VARCHAR2(30 BYTE), 
	"DATECREATION" DATE, 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."LABS" 
   (	"IDLABO" NUMBER, 
	"RESPONSABLE" VARCHAR2(255 BYTE), 
	"LOCALISATION" VARCHAR2(50 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"RESULTAT" VARCHAR2(255 BYTE), 
	"NOMLABO" VARCHAR2(50 BYTE), 
	"IDEMP" NUMBER, 
	"PAIEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PRODUCT" 
   (	"ID_PRODUCT" NUMBER, 
	"SKU" VARCHAR2(20 BYTE), 
	"QT_AV" NUMBER DEFAULT 0, 
	"QT_RS" NUMBER DEFAULT 0, 
	"THRESHOLD" NUMBER DEFAULT 0, 
	"SHELF" NUMBER, 
	"ZONE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"DESCR" VARCHAR2(50 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJETS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PROJETS" 
   (	"ID_PROJET" NUMBER, 
	"NOM_PROJET" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"OBJECTIFS" VARCHAR2(100 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN_PREVUE" DATE, 
	"DATE_FIN_REELLE" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"PRIORITE" VARCHAR2(20 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLICATIONS
--------------------------------------------------------

  CREATE TABLE "HICHEM"."PUBLICATIONS" 
   (	"ID_PUBLICATION" NUMBER, 
	"TITRE" VARCHAR2(500 BYTE), 
	"RESUME" VARCHAR2(2000 BYTE), 
	"INVENTEURS" VARCHAR2(500 BYTE), 
	"DOMAINE_FABRICATION" VARCHAR2(200 BYTE), 
	"TYPE_BREVET" VARCHAR2(100 BYTE), 
	"NUMERO_BREVET" NUMBER, 
	"DATE_DEPOT" DATE, 
	"STATUT_BREVET" VARCHAR2(50 BYTE) DEFAULT 'En cours', 
	"LIEN_DOCUMENT" VARCHAR2(100 BYTE), 
	"IDEMP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HICHEM.EMPLOYES
SET DEFINE OFF;
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('1','12345678','bo','Zak','ZAAK','5959bc63e1fbf0f1e5ff7d74884bf4b98310ec0f1fa9df459092e46e28bcb8fa','zak@gmail.com','RH','RH',to_date('26-03-27','RR-MM-DD'),'2300','RH',null,null,null,null,null,null,'aucun',null,null,null,'Absent','8');
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('5','12345269','BIB','IBI','BIBOU','0c777238aa36009fb82e30f0bf54d0a8751c735871f9b1d01664630ceb717102','bibou@mail.com','Chercheur','Recherche',to_date('26-03-27','RR-MM-DD'),'2800','Chercheur',null,null,null,null,null,null,'aucun',null,null,null,'Absent','10');
Insert into HICHEM.EMPLOYES (ID_EMPLOYE,CIN,NOM,PRENOM,USERNAME,PASSWORD_HASH,EMAIL,POSTE,DEPARTEMENT,DATE_EMBAUCHE,SALAIRE,ROLE,TYPE_DEMANDE,DATE_DEBUT,DATE_FIN,DESCRIPTION,DATE_DEMANDE,STATUT_DEMANDE,COMMENTAIRE_RH,DATE_POINTAGE,HEURE_ARRIVEE,HEURE_DEPART,STATUT_JOURNALIER,NB_ABSENCES) values ('6','12341234','Challakhi','Hichem','HICHEM','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4','hichem@finance.com','Comptable','Finance',to_date('00-01-01','RR-MM-DD'),'10000','Responsable_financier',null,null,null,null,null,null,'aucun',null,null,null,null,'0');
commit;
REM INSERTING into HICHEM.FINANCE
SET DEFINE OFF;
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('1','TRX-RPRO-260301-0001','Revenu','2000','Projet','Paiement client',to_date('26-03-01','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('2','TRX-DTRA-260302-0002','Depense','150','Transport','Taxi',to_date('26-03-02','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('3','TRX-DMAT-260303-0003','Depense','300','Materiel','Clavier',to_date('26-03-03','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('4','TRX-RCON-260304-0004','Revenu','2500','Consulting','Mission',to_date('26-03-04','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('5','TRX-DREP-260305-0005','Depense','80','Repas','Déjeuner',to_date('26-03-05','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('6','TRX-DMAI-260306-0006','Depense','500','Maintenance','Réparation',to_date('26-03-06','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('7','TRX-RPRO-260307-0007','Revenu','1800','Projet','App mobile',to_date('26-03-07','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('8','TRX-DINT-260308-0008','Depense','60','Internet','Facture',to_date('26-03-08','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('9','TRX-DTRA-260309-0009','Depense','220','Transport','Carburant',to_date('26-03-09','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('10','TRX-RPRO-260310-0010','Revenu','3000','Projet','SaaS',to_date('26-03-10','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('11','TRX-DREP-260311-0011','Depense','90','Repas','Dîner',to_date('26-03-11','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('12','TRX-DMAT-260312-0012','Depense','400','Materiel','Écran',to_date('26-03-12','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('13','TRX-RFOR-260313-0013','Revenu','1200','Formation','Workshop',to_date('26-03-13','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('14','TRX-DTRA-260314-0014','Depense','70','Transport','Taxi',to_date('26-03-14','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('15','TRX-DMAI-260315-0015','Depense','150','Maintenance','PC',to_date('26-03-15','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('16','TRX-RPRO-260316-0016','Revenu','2500','Projet','Dev logiciel',to_date('26-03-16','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('17','TRX-DINT-260317-0017','Depense','40','Internet','Recharge',to_date('26-03-17','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('18','TRX-DMAT-260318-0018','Depense','300','Materiel','Papeterie',to_date('26-03-18','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('19','TRX-RCON-260319-0019','Revenu','1800','Consulting','Audit',to_date('26-03-19','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('20','TRX-DREP-260320-0020','Depense','110','Repas','Client',to_date('26-03-20','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('21','TRX-DMAI-260321-0021','Depense','600','Maintenance','Écran',to_date('26-03-21','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('22','TRX-RPRO-260322-0022','Revenu','3500','Projet','Application',to_date('26-03-22','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('23','TRX-DTRA-260323-0023','Depense','85','Transport','Taxi urgent',to_date('26-03-23','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('24','TRX-DMAT-260324-0024','Depense','200','Materiel','Souris',to_date('26-03-24','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('25','TRX-RFOR-260325-0025','Revenu','950','Formation','Cours',to_date('26-03-25','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('26','TRX-DINT-260326-0026','Depense','75','Internet','Abonnement',to_date('26-03-26','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('27','TRX-DMAI-260327-0027','Depense','500','Maintenance','Serveur',to_date('26-03-27','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('28','TRX-RPRO-260328-0028','Revenu','2700','Projet','Site web',to_date('26-03-28','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('29','TRX-DREP-260329-0029','Depense','130','Repas','Equipe',to_date('26-03-29','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('30','TRX-RPRO-260330-0030','Revenu','4000','Projet','Big project',to_date('26-03-30','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('31','TRX-DTRA-260331-0031','Depense','95','Transport','Taxi nuit',to_date('26-03-31','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('32','TRX-RCON-260401-0032','Revenu','2100','Consulting','Audit SI',to_date('26-04-01','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('33','TRX-DMAT-260402-0033','Depense','350','Materiel','Disque dur',to_date('26-04-02','RR-MM-DD'),'carte_bancaire',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('34','TRX-RFOR-260403-0034','Revenu','1300','Formation','Bootcamp',to_date('26-04-03','RR-MM-DD'),'virement',to_date('26-03-27','RR-MM-DD'),'6');
Insert into HICHEM.FINANCE (IDFINANCE,CODETRANSA,TYPETRANSACTION,MONTANT,CATEGORIE,DESCRIPTION,DATETRANSACTION,MODEPAIEMENT,DATECREATION,IDEMP) values ('35','TRX-DREP-260404-0035','Depense','140','Repas','Déjeuner équipe',to_date('26-04-04','RR-MM-DD'),'especes',to_date('26-03-27','RR-MM-DD'),'6');
commit;
REM INSERTING into HICHEM.LABS
SET DEFINE OFF;
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT) values ('4','dqdsfg','36.89933812940674, 10.189509368854482','561','exterieur','Disponible','pr?t','zgfh','1','non payer');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT) values ('2','zak','morneg','92985300','exterieur','Occupe','En attente','vw','6','non payer');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT) values ('3','zak','36?49''38.7"N 10?08''50.1"E','44845113','interieur','Occupe','En attente','mercedes','1','payer');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT) values ('5','zza','36.82216689659118, 10.190769713391115','43','exterieur','Disponible','Pr?t','aaa','1','non payer');
Insert into HICHEM.LABS (IDLABO,RESPONSABLE,LOCALISATION,NUMERO,SPECIALITE,DISPONIBILITE,RESULTAT,NOMLABO,IDEMP,PAIEMENT) values ('6','saaaaas','36.82216689659118, 10.190769713391115','creec','exterieur','Occupe','En attente','asazas','1','payer');
commit;
REM INSERTING into HICHEM.PRODUCT
SET DEFINE OFF;
Insert into HICHEM.PRODUCT (ID_PRODUCT,SKU,QT_AV,QT_RS,THRESHOLD,SHELF,ZONE,STATUS,TYPE,NAME,UNIT,PRICE,DESCR,IDEMP) values ('1','ZER-232','0','0','0','0','B','on hand','Outil','TEST','kg','4','EAZR','1');
commit;
REM INSERTING into HICHEM.PROJETS
SET DEFINE OFF;
REM INSERTING into HICHEM.PUBLICATIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PUBLICATIONS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."PUBLICATIONS_UK1" ON "HICHEM"."PUBLICATIONS" ("TITRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007658
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007658" ON "HICHEM"."FINANCE" ("IDFINANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007670
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007670" ON "HICHEM"."LABS" ("IDLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007671
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007671" ON "HICHEM"."LABS" ("NOMLABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007677
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007677" ON "HICHEM"."PRODUCT" ("ID_PRODUCT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007678
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007678" ON "HICHEM"."PRODUCT" ("SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007682
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007682" ON "HICHEM"."PROJETS" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007687
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007687" ON "HICHEM"."PUBLICATIONS" ("ID_PUBLICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007834
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007834" ON "HICHEM"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007835
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007835" ON "HICHEM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007836
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007836" ON "HICHEM"."EMPLOYES" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007837
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."SYS_C007837" ON "HICHEM"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HICHEM"."UNIQUE_CODE" ON "HICHEM"."FINANCE" ("CODETRANSA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_TYPE_CHK" CHECK (TYPE_DEMANDE IN ('CONGE','FORMATION')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_STATUT_CHK" CHECK (STATUT_DEMANDE IN ('EN_ATTENTE','ACCEPTE','REFUSE')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_DATE_CHK" CHECK (DATE_DEBUT IS NULL OR DATE_FIN IS NULL OR DATE_DEBUT <= DATE_FIN) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" ADD CONSTRAINT "EMP_ROLE_CHK" CHECK (ROLE IN 
    ('Admin','Employe','RH','Responsable_financier','Responsable_de_stock','Chercheur','Directeur_de_projet','Responsable_Labos')) ENABLE;
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("DATE_EMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "UNIQUE_CODE" UNIQUE ("CODETRANSA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD PRIMARY KEY ("IDFINANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_MODE_CHK" CHECK (MODEPAIEMENT IN 
        ('especes','cheque','virement','carte_bancaire','facture','remboursement')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_TYPE_CHK" CHECK (TYPETRANSACTION IN ('Depense','Revenu')) ENABLE;
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATECREATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MODEPAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("DATETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("TYPETRANSACTION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."FINANCE" MODIFY ("CODETRANSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."LABS" MODIFY ("NOMLABO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" ADD UNIQUE ("NOMLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD PRIMARY KEY ("IDLABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_DISP_CHK" CHECK (DISPONIBILITE IN ('Disponible','Occupe')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" ADD CONSTRAINT "LABS_SPEC_CHK" CHECK (SPECIALITE IN ('interieur','exterieur')) ENABLE;
  ALTER TABLE "HICHEM"."LABS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("LOCALISATION" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."LABS" MODIFY ("RESPONSABLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD UNIQUE ("SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_STATUS_CHK" CHECK (STATUS IN ('on hand','limited','stock out')) ENABLE;
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PRODUCT" MODIFY ("SKU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_DATE_CHK" CHECK (
        DATE_FIN_REELLE IS NULL OR DATE_DEBUT < DATE_FIN_REELLE
    ) ENABLE;
  ALTER TABLE "HICHEM"."PROJETS" MODIFY ("NOM_PROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD PRIMARY KEY ("ID_PUBLICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUB_STATUT_CHK" CHECK (STATUT_BREVET IN ('En cours','Depose','Accepte','Refuse','Publie')) ENABLE;
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("IDEMP" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PUBLICATIONS" MODIFY ("TITRE" NOT NULL ENABLE);
  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUBLICATIONS_UK1" UNIQUE ("TITRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCE
--------------------------------------------------------

  ALTER TABLE "HICHEM"."FINANCE" ADD CONSTRAINT "FINANCE_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PRODUCT" ADD CONSTRAINT "PRODUCT_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PROJETS" ADD CONSTRAINT "PROJETS_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUBLICATIONS
--------------------------------------------------------

  ALTER TABLE "HICHEM"."PUBLICATIONS" ADD CONSTRAINT "PUB_FK" FOREIGN KEY ("IDEMP")
	  REFERENCES "HICHEM"."EMPLOYES" ("ID_EMPLOYE") ON DELETE CASCADE ENABLE;
